name: CI

# Controls when the workflow will run
on:
  repository_dispatch:
    types:
      - build-blog
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
        with:
          repository: 1221141/zola
          token: ${{ secrets.PAT }}
          path: origin

      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: main
          token: ${{ secrets.PAT  }}

      - name: rm
        run: rm -rf main/*

      - name: mv
        run: mv origin/public main/public

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: updated site
          repository: main
          steps:
